platform :ios, '10.0'
use_frameworks!

target 'Example' do

    pod 'DBClient/Realm', :path => '../'
    pod 'DBClient/CoreData', :path => '../'
end

target 'DBClientTests' do

    pod 'DBClient/Realm', :path => '../'
    pod 'DBClient/CoreData', :path => '../'
end
